"""initial"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('processing_jobs', sa.Column('id', sa.UUID(), primary_key=True), sa.Column('source_type', sa.String(20), nullable=False), sa.Column('original_filename', sa.Text()), sa.Column('display_filename', sa.Text(), nullable=False), sa.Column('stored_file_path', sa.Text(), nullable=False), sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False), sa.Column('recording_started_at', sa.DateTime(timezone=True)), sa.Column('status', sa.String(20), nullable=False), sa.Column('progress_percent', sa.Integer(), nullable=False, server_default='0'), sa.Column('current_step', sa.Text()), sa.Column('detected_languages', sa.ARRAY(sa.Text()), nullable=False, server_default='{}'), sa.Column('duration_seconds', sa.Float()), sa.Column('error_message', sa.Text()), sa.Column('cancel_requested', sa.Boolean(), nullable=False, server_default='false'), sa.Column('created_at', sa.DateTime(timezone=True)), sa.Column('updated_at', sa.DateTime(timezone=True)))
    op.create_table('transcript_segments', sa.Column('id', sa.UUID(), primary_key=True), sa.Column('job_id', sa.UUID(), sa.ForeignKey('processing_jobs.id', ondelete='CASCADE')), sa.Column('filename', sa.Text(), nullable=False), sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False), sa.Column('status', sa.String(20), nullable=False), sa.Column('start_seconds', sa.Float(), nullable=False), sa.Column('end_seconds', sa.Float(), nullable=False), sa.Column('language', sa.Text(), nullable=False), sa.Column('text', sa.Text(), nullable=False), sa.Column('speaker_label', sa.Text(), nullable=False), sa.Column('speaker_name', sa.Text()), sa.Column('speaker_vector', Vector(192)), sa.Column('text_embedding', Vector(768)), sa.Column('created_at', sa.DateTime(timezone=True)), sa.Column('updated_at', sa.DateTime(timezone=True)))
    op.create_table('speakers', sa.Column('id', sa.UUID(), primary_key=True), sa.Column('speaker_name', sa.Text(), nullable=False, unique=True), sa.Column('speaker_vector', Vector(192), nullable=False), sa.Column('samples_count', sa.Integer(), nullable=False, server_default='1'), sa.Column('created_at', sa.DateTime(timezone=True)), sa.Column('updated_at', sa.DateTime(timezone=True)))
    op.create_table('speaker_aliases', sa.Column('id', sa.UUID(), primary_key=True), sa.Column('job_id', sa.UUID(), sa.ForeignKey('processing_jobs.id', ondelete='CASCADE')), sa.Column('speaker_label', sa.Text(), nullable=False), sa.Column('speaker_name', sa.Text()), sa.Column('speaker_vector', Vector(192)), sa.Column('created_at', sa.DateTime(timezone=True)), sa.Column('updated_at', sa.DateTime(timezone=True)), sa.UniqueConstraint('job_id','speaker_label'))
    op.create_table('processing_events', sa.Column('id', sa.UUID(), primary_key=True), sa.Column('job_id', sa.UUID(), sa.ForeignKey('processing_jobs.id', ondelete='CASCADE')), sa.Column('event_type', sa.Text(), nullable=False), sa.Column('message', sa.Text(), nullable=False), sa.Column('payload', sa.JSON(), nullable=False, server_default='{}'), sa.Column('progress_percent', sa.Integer()), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.create_table('agent_messages', sa.Column('id', sa.UUID(), primary_key=True), sa.Column('job_id', sa.UUID(), sa.ForeignKey('processing_jobs.id', ondelete='CASCADE')), sa.Column('role', sa.Text(), nullable=False), sa.Column('content', sa.Text(), nullable=False), sa.Column('tool_name', sa.Text()), sa.Column('payload', sa.JSON(), nullable=False, server_default='{}'), sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
def downgrade():
    for t in ['agent_messages','processing_events','speaker_aliases','speakers','transcript_segments','processing_jobs']: op.drop_table(t)
