from typing import Protocol, AsyncIterator
class AsyncModelClient(Protocol):
    async def embed(self, texts: list[str]) -> list[list[float]]: ...
    async def rerank(self, query: str, docs: list[str]) -> list[int]: ...
    def stream_chat(self, messages: list[dict]) -> AsyncIterator[str]: ...
