from collections.abc import AsyncIterator
from typing import Protocol


class AsyncModelClient(Protocol):
    async def embed(self, texts: list[str]) -> list[list[float]]: ...
    async def rerank(self, query: str, docs: list[str]) -> list[int]: ...
    async def complete(self, messages: list[dict[str, str]], temperature: float = 0.1) -> str: ...
    def stream(self, messages: list[dict[str, str]], temperature: float = 0.1) -> AsyncIterator[str]: ...
