from typing import Protocol, Any
from uuid import UUID
class JobRepository(Protocol): ...
class TranscriptRepository(Protocol): ...
class SpeakerRepository(Protocol): ...
class UnitOfWork(Protocol):
    jobs: Any; transcripts: Any; speakers: Any
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc, tb): ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
