from enum import StrEnum
class SourceType(StrEnum): UPLOAD="UPLOAD"; RECORDING="RECORDING"
class JobStatus(StrEnum): PENDING="PENDING"; PROCESSING="PROCESSING"; SUCCESS="SUCCESS"; ERROR="ERROR"; CANCELLED="CANCELLED"
